//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRINGUP_Proj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izvjestaj
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public string Members_present { get; set; }
        public string Location { get; set; }
        public string Duration { get; set; }
        public string Date_Posted { get; set; }
        public string Date_Edited { get; set; }
        public string User_ID { get; set; }
        public string Username { get; set; }
    }
}
