//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRINGUP_Proj.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IzvjestajiEntities1 : DbContext
    {
        public IzvjestajiEntities1()
            : base("name=IzvjestajiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Izvjestaj> Izvjestajs { get; set; }

        public System.Data.Entity.DbSet<PRINGUP_Proj.Models.Lists> Lists { get; set; }
    }
}
