//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRINGUP_Proj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lists
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public string Date_Posted { get; set; }
        public string Time_Posted { get; set; }
        public string Date_Edited { get; set; }
        public string Time_Edited { get; set; }
        public int User_Id { get; set; }
    }
}
